@Library('jenkins-upstream-library') _

pipeline {
    agent {
        kubernetes {
            inheritFrom 'jenkins-agent'
        }
    }
    stages {
        stage('Test') {
            steps {
                echo "Test step"
            }
        }
    }
}
